name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install nix
      uses: cachix/install-nix-action@v6
    - name: Install
      run: |
        nix-shell --run "make dev-install"
    - name: Run tests
      run: |
        nix-shell --run "make test"
